### ISSUE TITLE
[exp-8] propagazione errori

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/lab1-dfa#57]

**Comment by dennisangemi** [comment]
![20220427_103226](https://user-images.githubusercontent.com/77018886/165477261-e2a2251d-ae87-44fd-a78d-db53c7d2852e.jpg)

**Comment by dennisangemi** [comment]
# Da correggere

**Comment by fedeingrassia** [comment]
![2659693F-B8D4-4D20-AE00-677488AD8779](https://user-images.githubusercontent.com/101574543/170217107-f9b7e73b-eaf7-4042-b0a3-abc53afdb0c0.png)


Corretta
